version: '2'
services:
  node4:
    image: node:4.4
    container_name: node4
    hostname: node4-dev
    command: node /usr/src/app/index.js
    links:
      - "mongo"
      - "percona"
    expose:
      - 3000
    ports:
      - 3000:3000
    volumes:
      - "./node4:/usr/src/app"
  
  redis:
    image: redis
    hostname: redis_share
    expose:
     - 6379
  mongo:
    image: mongo
    hostname: mongo_share
    expose:
      - 27017
    volumes:
      - "./share_data/mongo_data:/data/db"
  percona:
     image: percona
     hostname:  percona_share
     expose:
      - 3306
     volumes:
      - "./share_data/mysql_data:/var/lib/mysql"
     environment:
      - MYSQL_ROOT_PASSWORD=root

  node5:
    image: node:5.11
    container_name: node5
    hostname: node5-dev
    command:  node /usr/src/app/index.js
    links:
      - "percona"
      - "mongo"
    expose:
      - 3000
    ports:
      - 3001:3000
    volumes:
      - "./node5:/usr/src/app"
